x = document.querySelector("title");
a = document.querySelector(".but1");
b = document.querySelector(".but2");
c = document.querySelector(".but3");
d = document.querySelector(".but4");
e = document.querySelector(".but5");
f = document.querySelector(".but6");
g = document.querySelector(".but7");
villain = document.querySelector(".but71");

x.innerHTML="Villain";
a.innerHTML="Bangla Plex";
b.innerHTML="PCV";
c.innerHTML="Chocolate";
d.innerHTML="Media PLEX";
e.innerHTML="FNF Online";
f.innerHTML="Drive Movie";
g.innerHTML="Development";
villain.innerHTML="Black Web 71";
